### ISSUE TITLE
ableton/Link.hpp not found

### ISSUE THREAD

**Issue by cuinjune** [2bbb/ofxAbletonLink#1]
Hi, I tried to use ofxAbletonLink but it cannot find the Link.hpp file.

Maybe the file no longer exist in the latest version of Ableton Link?
I downloaded LinkKit, and there are only 3 files in include folder that are ABLLink.h, ABLLinkSettingsViewController.h and ABLLinkUtils.h.

Am I missing something or is ofxAbletonLink no longer being maintained?

Thanks.

**Comment by 2bbb** [comment]
@cuinjune 
you must read README.md and study git.

**Comment by cuinjune** [comment]
Sorry, I should have mentioned that I'm trying to use ofxAbletonLink with LinkKit which is an iOS SDK for Ableton Link. But it seems like it is not possible. I will find other ways. Thanks.

**Comment by 2bbb** [comment]
@cuinjune 

don't worry :)

i don't try LinkKit, but maybe we can use this addon for ofxiOS, maybe.
