### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by gilfuser** [2bbb/ofxAbletonLink#3]
Hi.
Really looking forward into having this working.
When I try to do this, following the README:
`git clone git@github.com:2bbb/ofxAbletonLink.git`
I got this:
Permission denied (publickey).

But if I do `git clone https://github.com/2bbb/ofxAbletonLink.git`
it works. Then I `cd ofxAbletonLink`
and... `git submodule update --init --recursive`
I got something like this (google-translated from German to English)
```
Submodule 'libs / link' (git@github.com: Ableton / link.git) for path 'libs / link' into the configuration.
Clones to '/ home / gilfuser / builds / ofxAbletonLink / libs / link' ...
Permission denied (publickey).
fatal: Could not read from the remote repository.

Please ensure that the correct access rights exist
and the repository exists.
fatal: Cloning of 'git@github.com: Ableton / link.git' in submodule path '/ home / gilfuser / builds / ofxAbletonLink / libs / link' failed
Error while cloning 'libs / link'. Further experiment planned
Clones to '/ home / gilfuser / builds / ofxAbletonLink / libs / link' ...
Permission denied (publickey).
fatal: Could not read from the remote repository.

Please ensure that the correct access rights exist
and the repository exists.
fatal: Cloning of 'git@github.com: Ableton / link.git' in submodule path '/ home / gilfuser / builds / ofxAbletonLink / libs / link' failed
Second attempt to clone 'libs / link' failed, break off.
```
It's just me missing something basic about the way Github works, or there is something wrong with the repo? Or both?

bests,
Gil

**Comment by 2bbb** [comment]
@gilfuser 

hi.

did you setup ssh key on your PC with github account?

**Comment by gilfuser** [comment]
Ah Ok. I tried but something went wrong. I was following the forum and did
not really understand what I was doing. I'm going to try again and come
back later to tell if I got it.

Am Mo., 16. Okt. 2017, 18:54 schrieb ISHII 2bit <notifications@github.com>:

**Comment by 2bbb** [comment]
@gilfuser 

hi, Gil.

i published branch with `dev/permission_denied`.

please try:

```
git clone https://github.com/2bbb/ofxAbletonLink.git
cd ofxAbletonLink
git checkout -b dev/permission_denied origin/dev/permission_denied 
git submodule update --init --recursive
```

best.

**Comment by gilfuser** [comment]
That did it!
Thank you!
PS: I still need to learn about that permission thing in git, though

bests

**Comment by 2bbb** [comment]
@gilfuser 

yeah!
i will merge it to master.

so, i'm not specialist of git.
but i think, maybe it is caused by ssh key.
did you create ssh key on terminal with `ssh-keygen` and set public key `SSH and GPG keys`on github?
if you do it then maybe it will be solve, maybe, maybe.

but, this change is more better solution for only use.

thanks.
