### ISSUE TITLE
working with tracks?

### ISSUE THREAD

**Issue by paul-ferragut** [2bbb/ofxAbletonLink#6]
Thank you for this addon!
Would it be possible to get the tracks and change their properties?
I mean the same sort of features and usage as in https://github.com/genekogan/ofxAbletonLive

**Comment by 2bbb** [comment]
@paul-ferragut 

unfortunately, answer is "NO".
this addon is only for sync with [Ableton Link](https://www.ableton.com/en/link/).

thanks.
